// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTSvOwwaAV6pvi_CCS83_IG6H6TKYuUaw',
    appId: '1:197513505238:web:cb7f7c2362927cc6169c77',
    messagingSenderId: '197513505238',
    projectId: 'flutter-project-torque-85cc2',
    authDomain: 'flutter-project-torque-85cc2.firebaseapp.com',
    storageBucket: 'flutter-project-torque-85cc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClBgH_txW9Zn6C-mEIw0zifZXOutCHsPo',
    appId: '1:197513505238:android:f36d995920e4a385169c77',
    messagingSenderId: '197513505238',
    projectId: 'flutter-project-torque-85cc2',
    storageBucket: 'flutter-project-torque-85cc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAycWK-VjyzFECcuFt-UUar93oOgIV_41Y',
    appId: '1:197513505238:ios:77adab52d7c660b3169c77',
    messagingSenderId: '197513505238',
    projectId: 'flutter-project-torque-85cc2',
    storageBucket: 'flutter-project-torque-85cc2.firebasestorage.app',
    iosBundleId: 'com.example.moto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAycWK-VjyzFECcuFt-UUar93oOgIV_41Y',
    appId: '1:197513505238:ios:77adab52d7c660b3169c77',
    messagingSenderId: '197513505238',
    projectId: 'flutter-project-torque-85cc2',
    storageBucket: 'flutter-project-torque-85cc2.firebasestorage.app',
    iosBundleId: 'com.example.moto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTSvOwwaAV6pvi_CCS83_IG6H6TKYuUaw',
    appId: '1:197513505238:web:ff9465fa9ab8872e169c77',
    messagingSenderId: '197513505238',
    projectId: 'flutter-project-torque-85cc2',
    authDomain: 'flutter-project-torque-85cc2.firebaseapp.com',
    storageBucket: 'flutter-project-torque-85cc2.firebasestorage.app',
  );
}
